import './style.scss';
import 'normalize.css';

import { H1 } from './components/h1/index';
import { render } from './utils/render';
import { Form } from './components/form/index';
import { Link } from './components/link/index';
import { Popup } from './components/popup/index';
import { Avatar } from './components/avatar/index';
import { Button } from './components/button/index';
import { AddFile } from './components/addFile/index';
import { Wrapper } from './components/wrapper/index';
import { ChatItem } from './components/chatItem/index';
import { UserProfile } from './pages/userProfile/index';
import { Paragraph } from './components/paragraph/index';
import { InputBlock } from './components/inputBlock/index';
import { SendButton } from './components/sendButton/index';
import { SearchInput } from './components/searchInput/index';
import { InputElement } from './components/inputElement/index';
import { AddFileButton } from './components/addFileButton/index';
import { AddUserButton } from './components/addUserButton/index';
import { InMessageItem } from './components/inMessageItem/index';
import { OutMessageItem } from './components/outMessageItem/index';
import { registerComponent } from './utils/resgiterComponent';
import { NewMessageInput } from './components/newMessageInput/index';
import { NewMessageBlock } from './components/newMessageBlock/index';
import { UserProfileForm } from './components/userProfileForm/index';
import { UserProfileAvatar } from './components/userProfileAvatar/index';
import { UserProfileInputBlock } from './components/userProfileInputBlock/index';
import { UnreadMessageIndicator } from './components/unreadMessageIndicator/index';

registerComponent('H1', H1);
registerComponent('Form', Form);
registerComponent('Link', Link);
registerComponent('Popup', Popup);
registerComponent('Button', Button);
registerComponent('Avatar', Avatar);
registerComponent('AddFile', AddFile);
registerComponent('Wrapper', Wrapper);
registerComponent('ChatItem', ChatItem);
registerComponent('Paragraph', Paragraph);
registerComponent('InputBlock', InputBlock);
registerComponent('SendButton', SendButton);
registerComponent('UserProfile', UserProfile);
registerComponent('SearchInput', SearchInput);
registerComponent('InputElement', InputElement);
registerComponent('AddFileButton', AddFileButton);
registerComponent('AddUserButton', AddUserButton);
registerComponent('InMessageItem', InMessageItem);
registerComponent('OutMessageItem', OutMessageItem);
registerComponent('NewMessageBlock', NewMessageBlock);
registerComponent('NewMessageInput', NewMessageInput);
registerComponent('UserProfileForm', UserProfileForm);
registerComponent('UserProfileAvatar', UserProfileAvatar);
registerComponent('UserProfileInputBlock', UserProfileInputBlock);
registerComponent('UnreadMessageIndicator', UnreadMessageIndicator);

window.addEventListener('DOMContentLoaded', () => {
  render('home');
});
