import './style.scss';
import 'normalize.css';

import { render } from './utils/render';
import { H1 } from './components/h1';
import { Form } from './components/form';
import { Link } from './components/link';
import { Popup } from './components/popup';
import { Avatar } from './components/avatar';
import { Button } from './components/Button';
import { AddFile } from './components/addFile';
import { Wrapper } from './components/wrapper';
import { ChatItem } from './components/chatItem';
import { UserProfile } from './pages/userProfile';
import { Paragraph } from './components/paragraph';
import { InputBlock } from './components/inputBlock';
import { SendButton } from './components/sendButton';
import { SearchInput } from './components/searchInput';
import { registerComponent } from './utils/resgiterComponent';
import { InputElement } from './components/inputElement';
import { AddFileButton } from './components/addFileButton';
import { AddUserButton } from './components/addUserButton';
import { InMessageItem } from './components/inMessageItem';
import { OutMessageItem } from './components/outMessageItem';
import { NewMessageInput } from './components/newMessageInput';
import { NewMessageBlock } from './components/newMessageBlock';
import { UserProfileForm } from './components/userProfileForm';
import { UserProfileAvatar } from './components/userProfileAvatar';
import { UserProfileInputBlock } from './components/userProfileInputBlock';
import { UnreadMessageIndicator } from './components/unreadMessageIndicator';

registerComponent('H1', H1);
registerComponent('Form', Form);
registerComponent('Link', Link);
registerComponent('Popup', Popup);
registerComponent('Button', Button);
registerComponent('Avatar', Avatar);
registerComponent('AddFile', AddFile);
registerComponent('Wrapper', Wrapper);
registerComponent('ChatItem', ChatItem);
registerComponent('Paragraph', Paragraph);
registerComponent('InputBlock', InputBlock);
registerComponent('SendButton', SendButton);
registerComponent('UserProfile', UserProfile);
registerComponent('SearchInput', SearchInput);
registerComponent('InputElement', InputElement);
registerComponent('AddFileButton', AddFileButton);
registerComponent('AddUserButton', AddUserButton);
registerComponent('InMessageItem', InMessageItem);
registerComponent('OutMessageItem', OutMessageItem);
registerComponent('NewMessageBlock', NewMessageBlock);
registerComponent('NewMessageInput', NewMessageInput);
registerComponent('UserProfileForm', UserProfileForm);
registerComponent('UserProfileAvatar', UserProfileAvatar);
registerComponent('UserProfileInputBlock', UserProfileInputBlock);
registerComponent('UnreadMessageIndicator', UnreadMessageIndicator);

window.addEventListener('DOMContentLoaded', () => {
  render('home');
});
