export const chatPage = {
  longMessage: 'Привет! Смотри, тут всплыл интересный кусок лунной космической истории — НАСА в какой-то момент попросила Хассельблад адаптировать модель SWC для полетов на Луну. Сейчас мы все знаем что астронавты летали с моделью 500 EL — и к слову говоря, все тушки этих камер все еще находятся на поверхности Луны, так как астронавты с собой забрали только кассеты с пленкой.\n' +
    '\n' +
    'Хассельблад в итоге адаптировал SWC для космоса, но что-то пошло не так и на ракету они так никогда и не попали. Всего их было произведено 25 штук, одну из них недавно продали на аукционе за 45000 евро.',
  chatList: [
    {
      avatarUrl: '',
      chatName: 'Андрей',
      lastMessage: 'Изображение',
      isLastMessageOutgoing: '',
      lastMessageTime: '10:49',
      unreadMessages: 2,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: 'Киноклуб',
      lastMessage: 'стикер',
      isLastMessageOutgoing: 'outgoing',
      lastMessageTime: '12:00',
      unreadMessages: 0,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: 'Илья',
      lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!...',
      isLastMessageOutgoing: '',
      lastMessageTime: '15:12',
      unreadMessages: 4,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: 'Вадим',
      lastMessage: 'Круто!',
      isLastMessageOutgoing: 'outgoing',
      lastMessageTime: 'Пт',
      unreadMessages: 0,
      selected: 'chat-item_selected',
    },
    {
      avatarUrl: '',
      chatName: 'тет-а-теты',
      lastMessage: 'И Human Interface Guidelines и Material Design рекомендуют...',
      isLastMessageOutgoing: '',
      lastMessageTime: 'Ср',
      unreadMessages: 0,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: '1, 2, 3',
      lastMessage: 'Миллионы россиян ежедневно проводят десятки часов свое...',
      isLastMessageOutgoing: '',
      lastMessageTime: 'Пн',
      unreadMessages: 0,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: 'Design Destroyer',
      lastMessage: 'В 2008 году художник Jon Rafman начал собирать...',
      isLastMessageOutgoing: '',
      lastMessageTime: 'Пн',
      unreadMessages: 0,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: 'Day.',
      lastMessage: 'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
      isLastMessageOutgoing: '',
      lastMessageTime: '1 Мая 2020',
      unreadMessages: 0,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: 'Стас Рогозин',
      lastMessage: 'Можно или сегодня или завтра вечером.',
      isLastMessageOutgoing: '',
      lastMessageTime: '12 Апр 2020',
      unreadMessages: 0,
      selected: '',
    },
  ],
}
