export const chatPage = {
  longMessage: 'Привет! Смотри, тут всплыл интересный кусок лунной космической истории — НАСА в какой-то момент попросила Хассельблад адаптировать модель SWC для полетов на Луну. Сейчас мы все знаем что астронавты летали с моделью 500 EL — и к слову говоря, все тушки этих камер все еще находятся на поверхности Луны, так как астронавты с собой забрали только кассеты с пленкой.\n' +
    '\n' +
    'Хассельблад в итоге адаптировал SWC для космоса, но что-то пошло не так и на ракету они так никогда и не попали. Всего их было произведено 25 штук, одну из них недавно продали на аукционе за 45000 евро.',
  chatList: [
    {
      avatarUrl: '',
      chatName: 'Андрей',
      lastMessage: 'Изображение',
      isLastMessageOutgoing: '',
      lastMessageTime: '10:49',
      unreadMessages: 2,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: 'Киноклуб',
      lastMessage: 'стикер',
      isLastMessageOutgoing: 'outgoing',
      lastMessageTime: '12:00',
      unreadMessages: 0,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: 'Илья',
      lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!...',
      isLastMessageOutgoing: '',
      lastMessageTime: '15:12',
      unreadMessages: 4,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: 'Вадим',
      lastMessage: 'Круто!',
      isLastMessageOutgoing: 'outgoing',
      lastMessageTime: 'Пт',
      unreadMessages: 0,
      selected: 'chat-item_selected',
    },
    {
      avatarUrl: '',
      chatName: 'тет-а-теты',
      lastMessage: 'И Human Interface Guidelines и Material Design рекомендуют...',
      isLastMessageOutgoing: '',
      lastMessageTime: 'Ср',
      unreadMessages: 0,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: '1, 2, 3',
      lastMessage: 'Миллионы россиян ежедневно проводят десятки часов свое...',
      isLastMessageOutgoing: '',
      lastMessageTime: 'Пн',
      unreadMessages: 0,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: 'Design Destroyer',
      lastMessage: 'В 2008 году художник Jon Rafman начал собирать...',
      isLastMessageOutgoing: '',
      lastMessageTime: 'Пн',
      unreadMessages: 0,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: 'Day.',
      lastMessage: 'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
      isLastMessageOutgoing: '',
      lastMessageTime: '1 Мая 2020',
      unreadMessages: 0,
      selected: '',
    },
    {
      avatarUrl: '',
      chatName: 'Стас Рогозин',
      lastMessage: 'Можно или сегодня или завтра вечером.',
      isLastMessageOutgoing: '',
      lastMessageTime: '12 Апр 2020',
      unreadMessages: 0,
      selected: '',
    },
  ],
}

const chatList = [
  {
    avatarUrl: '',
    chatName: 'Андрей',
    messages: [
      {
        imageUrl: '',
        messageText: 'Привет, как дела?',
        sendTime: '10:00',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Привет, все хорошо, спасибо. А у тебя?',
        sendTime: '10:02',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Да, все отлично. Спасибо за спрос!',
        sendTime: '10:05',
        isMessageOutgoing: true,
      },
    ],
    unreadMessages: 2,
  },
  {
    avatarUrl: '',
    chatName: 'Киноклуб',
    messages: [
      {
        imageUrl: '',
        messageText: 'Привет, как дела?',
        sendTime: '12:00',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Привет, все хорошо, спасибо. А у тебя?',
        sendTime: '12:02',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Да, все отлично. Спасибо за спрос!',
        sendTime: '12:05',
        isMessageOutgoing: false,
      },
    ],
    unreadMessages: 0,
  },
  {
    avatarUrl: '',
    chatName: 'Илья',
    messages: [
      {
        imageUrl: '',
        messageText: 'Привет, как дела?',
        sendTime: '15:00',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Привет, все хорошо, спасибо. А у тебя?',
        sendTime: '15:02',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Да, все отлично. Спасибо за спрос!',
        sendTime: '15:05',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'А у тебя какие новости?',
        sendTime: '15:10',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Ничего особенного, работаю как обычно.',
        sendTime: '15:12',
        isMessageOutgoing: false,
      },
    ],
    unreadMessages: 4,
  },
  {
    avatarUrl: '',
    chatName: 'Вадим',
    messages: [
      {
        imageUrl: '',
        messageText: 'Привет, как дела?',
        sendTime: '16:00',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Привет, все хорошо, спасибо. А у тебя?',
        sendTime: '16:02',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Да, все отлично. Спасибо за спрос!',
        sendTime: '16:05',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Как проходит работа?',
        sendTime: '16:10',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Да, все идет по плану. Спасибо за интерес!',
        sendTime: '16:12',
        isMessageOutgoing: false,
      },
    ],
    unreadMessages: 0,
  },
  {
    avatarUrl: '',
    chatName: 'тет-а-теты',
    messages: [
      {
        imageUrl: '',
        messageText: 'Привет, как дела?',
        sendTime: '17:00',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Привет, все хорошо, спасибо. А у тебя?',
        sendTime: '17:02',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Да, все отлично. Спасибо за спрос!',
        sendTime: '17:05',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Как твои дела?',
        sendTime: '17:10',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Да, все хорошо. Спасибо за интерес!',
        sendTime: '17:12',
        isMessageOutgoing: true,
      },
    ],
    unreadMessages: 0,
  },
  {
    avatarUrl: '',
    chatName: '1, 2, 3',
    messages: [
      {
        imageUrl: '',
        messageText: 'Привет, как дела?',
        sendTime: '18:00',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Привет, все хорошо, спасибо. А у тебя?',
        sendTime: '18:02',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Да, все отлично. Спасибо за спрос!',
        sendTime: '18:05',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Как твои дела?',
        sendTime: '18:10',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Да, все хорошо. Спасибо за интерес!',
        sendTime: '18:12',
        isMessageOutgoing: true,
      },
    ],
    unreadMessages: 0,
  },
  {
    avatarUrl: '',
    chatName: 'Design Destroyer',
    messages: [
      {
        imageUrl: '',
        messageText: 'Привет, как дела?',
        sendTime: '10:00',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Привет, все хорошо, спасибо. А у тебя?',
        sendTime: '10:02',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Да, все отлично. Спасибо за спрос!',
        sendTime: '10:05',
        isMessageOutgoing: true,
      },
    ],
    unreadMessages: 0,
  },
  {
    avatarUrl: '',
    chatName: 'Day.',
    messages: [
      {
        imageUrl: '',
        messageText: 'Привет, как дела?',
        sendTime: '15:00',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Привет, все хорошо, спасибо. А у тебя?',
        sendTime: '15:02',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Да, все отлично. Спасибо за спрос!',
        sendTime: '15:05',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Так увлёкся работой по курсу, что совсем забыл его анонсировать. Как успехи у тебя?',
        sendTime: '15:10',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Да, у меня все идет хорошо, спасибо за интерес. Курс очень понравился!',
        sendTime: '15:12',
        isMessageOutgoing: false,
      },
    ],
    unreadMessages: 0,
  },
  {
    avatarUrl: '',
    chatName: 'Стас Рогозин',
    messages: [
      {
        imageUrl: '',
        messageText: 'Привет, как дела?',
        sendTime: '12:00',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Привет, все хорошо, спасибо. А у тебя?',
        sendTime: '12:02',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Да, все отлично. Спасибо за спрос!',
        sendTime: '12:05',
        isMessageOutgoing: false,
      },
      {
        imageUrl: '',
        messageText: 'Когда можешь встретиться?',
        sendTime: '12:10',
        isMessageOutgoing: true,
      },
      {
        imageUrl: '',
        messageText: 'Можно или сегодня или завтра вечером.',
        sendTime: '12:12',
        isMessageOutgoing: false,
      },
    ],
    unreadMessages: 0,
  },
];
