export const registrationInputsBlockData = [
  {
    error: '',
    name: 'email',
    for: 'email',
    type: 'text',
    placeholder: 'Почта',
    value: 'pochta@yandex.ru',
    errorText: 'Неверный почта',
    errorClass: '',
  },
  {
    error: '',
    name: 'login',
    for: 'login',
    type: 'text',
    placeholder: 'Логин',
    value: 'ivanivanov',
    errorText: 'Неверный логин',
    errorClass: '',
  },
  {
    error: '',
    name: 'first_name',
    for: 'first_name',
    type: 'text',
    placeholder: 'Имя',
    value: 'Иван',
    errorText: '',
    errorClass: '',
  },
  {
    error: '',
    name: 'second_name',
    for: 'second_name',
    type: 'text',
    placeholder: 'Фамилия',
    value: 'Иванов',
    errorText: '',
    errorClass: '',
  },
  {
    error: '',
    name: 'phone',
    for: 'phone',
    type: 'text',
    placeholder: 'Телефон',
    value: '+7 (909) 967 30 30',
    errorText: '',
    errorClass: '',
  },
  {
    error: 'true',
    name: 'password',
    for: 'password',
    type: 'password',
    placeholder: 'Пароль',
    value: '111112',
    errorText: '',
    errorClass: 'reg-form_input-error',
  },
  {
    error: 'true',
    name: 'rep_password',
    for: 'rep_password',
    type: 'password',
    placeholder: 'Пароль (ещё раз)',
    value: '123456789',
    errorText: 'Пароли не совпадают',
    errorClass: 'reg-form_input-error',
  },
];
