export const userProfilePage = {
  userProfileInputBlockData: [
    {
      header: 'Почта',
      disabled: 'true',
      id: 'email',
      name: 'email',
      type: 'text',
      value: 'pochta@yandex.ru',
    },
    {
      header: 'Логин',
      disabled: 'true',
      id: 'login',
      name: 'login',
      type: 'text',
      value: 'ivanivanov',
    },
    {
      header: 'Имя',
      disabled: 'true',
      id: 'first_name',
      name: 'firstName',
      type: 'text',
      value: 'Иван',
    },
    {
      header: 'Фамилия',
      disabled: 'true',
      id: 'second_name',
      name: 'second_name',
      type: 'text',
      value: 'Иванов',
    },
    {
      header: 'Имя в чате',
      disabled: 'true',
      id: 'display_name',
      name: 'display_name',
      type: 'text',
      value: 'Иван',
    },
    {
      header: 'Телефон',
      disabled: 'true',
      id: 'phone',
      name: 'phone',
      type: 'text',
      value: '+7 (909) 967 30 30',
      class: 'last',
    },
  ],
  userProfilePasswordBlock: [
    {
      header: 'Старый пароль',
      id: 'oldPassword',
      name: 'oldPassword',
      type: 'password',
      value: '1111111',
    },
    {
      header: 'Новый пароль',
      id: 'newPassword',
      name: 'newPassword',
      type: 'password',
      value: '123456789',
    },
    {
      header: 'Повторите новый пароль',
      id: 'repeatNewPassword',
      name: 'repeatNewPassword',
      type: 'password',
      value: '123456789',
      class: 'last',
    },
  ],
  userProfileChangeLinks: [
    {
      header: 'Изменить данные',
      isShowButton: 'true',
      class: 'user-profile_change-data-button',
    },
    {
      header: 'Изменить пароль',
      isShowButton: 'true',
      class: 'user-profile_change-password-button',
    },
  ],
};
