export enum USER_PROFILE_REFS {
  EMAIL = 'email',
  LOGIN = 'login',
  FIRST_NAME = 'first_name',
  SECOND_NAME = 'second_name',
  DISPLAY_NAME = 'display_name',
  PHONE = 'phone',
  PASSWORD = 'password',
  OLD_PASSWORD = 'oldPassword',
  NEW_PASSWORD = 'newPassword',
  REP_NEW_PASSWORD = 'repNewPasswordInput',
}

export type TUserProfilePage = typeof userProfilePageData;

export const userProfilePageData = {
  fileExtension: ['jpg', 'jpeg', 'png'],
  saveButtonInnerText: 'Сохранить',
  userProfileInputBlockData: [
    {
      ref: USER_PROFILE_REFS.EMAIL,
      regex: '',
      required: true,
      header: 'Почта',
      id: 'email',
      name: 'email',
      type: 'text',
      value: '',
      class: 'block_input block_input_no-background font_13',
    },
    {
      ref: USER_PROFILE_REFS.LOGIN,
      regex: '',
      required: true,
      header: 'Логин',
      id: 'login',
      name: 'login',
      type: 'text',
      value: '',
      class: 'block_input block_input_no-background font_13',
    },
    {
      ref: USER_PROFILE_REFS.FIRST_NAME,
      regex: '',
      required: true,
      header: 'Имя',
      id: 'first_name',
      name: 'firstName',
      type: 'text',
      value: '',
      class: 'block_input block_input_no-background font_13',
    },
    {
      ref: USER_PROFILE_REFS.SECOND_NAME,
      regex: '',
      required: true,
      header: 'Фамилия',
      id: 'second_name',
      name: 'second_name',
      type: 'text',
      value: '',
      class: 'block_input block_input_no-background font_13',
    },
    {
      ref: USER_PROFILE_REFS.DISPLAY_NAME,
      regex: '',
      required: true,
      header: 'Имя в чате',
      id: 'display_name',
      name: 'display_name',
      type: 'text',
      value: '',
      class: 'block_input block_input_no-background font_13',
    },
    {
      ref: USER_PROFILE_REFS.PHONE,
      regex: '',
      required: true,
      header: 'Телефон',
      id: 'phone',
      name: 'phone',
      type: 'text',
      value: '',
      class: 'last block_input block_input_no-background font_13',
    },
  ],
  userProfileInputsNames: [
    USER_PROFILE_REFS.EMAIL,
    USER_PROFILE_REFS.LOGIN,
    USER_PROFILE_REFS.FIRST_NAME,
    USER_PROFILE_REFS.SECOND_NAME,
    USER_PROFILE_REFS.DISPLAY_NAME,
    USER_PROFILE_REFS.PHONE,
  ],
  userProfilePasswordBlock: [
    {
      ref: USER_PROFILE_REFS.OLD_PASSWORD,
      regex: '',
      required: true,
      header: 'Старый пароль',
      id: 'oldPassword',
      name: 'oldPassword',
      type: 'password',
      value: '',
      class: 'block_input block_input_no-background font_13',
    },
    {
      ref: USER_PROFILE_REFS.NEW_PASSWORD,
      regex: '',
      required: true,
      header: 'Новый пароль',
      id: 'newPassword',
      name: 'newPassword',
      type: 'password',
      value: '',
      class: 'block_input block_input_no-background font_13',
    },
    {
      ref: USER_PROFILE_REFS.REP_NEW_PASSWORD,
      regex: '',
      required: true,
      header: 'Повторите новый пароль',
      id: 'repeatNewPassword',
      name: 'repeatNewPassword',
      type: 'password',
      value: '',
      class: 'last block_input block_input_no-background font_13',
    },
  ],
  userProfilePasswordBlockInputNames: [
    USER_PROFILE_REFS.OLD_PASSWORD,
    USER_PROFILE_REFS.NEW_PASSWORD,
  ],
  userProfileChangeLinks: {
    changeUserData: {
      header: 'Изменить данные',
      isShowButton: 'true',
      class: 'user-profile_change-data-button',
    },
    changeUserPassword: {
      header: 'Изменить пароль',
      isShowButton: 'true',
      class: 'user-profile_change-password-button',
    },
  },
};
