export enum USER_PROFILE_REFS {
  EMAIL = 'emailInput',
  LOGIN = 'loginInput',
  FIRST_NAME = 'firstNameInput',
  SECOND_NAME = 'secondNameInput',
  DISPLAY_NAME = 'displayNameInput',
  PHONE = 'phoneInput',
  PASSWORD = 'passwordInput',
  NEW_PASSWORD = 'newPasswordInput',
  REP_NEW_PASSWORD = 'repNewPasswordInput',
}

export const userProfilePage = {
  saveButtonInnerText: 'Сохранить',
  userProfileInputBlockData: [
    {
      ref: USER_PROFILE_REFS.EMAIL,
      regex: '',
      required: true,
      header: 'Почта',
      disabled: 'true',
      id: 'email',
      name: 'email',
      type: 'text',
      value: 'pochta@yandex.ru',
      class: 'block_input block_input_no-background font_13'
    },
    {
      ref: USER_PROFILE_REFS.LOGIN,
      regex: '',
      required: true,
      header: 'Логин',
      disabled: 'true',
      id: 'login',
      name: 'login',
      type: 'text',
      value: 'ivanivanov',
      class: 'block_input block_input_no-background font_13'
    },
    {
      ref: USER_PROFILE_REFS.FIRST_NAME,
      regex: '',
      required: true,
      header: 'Имя',
      disabled: 'true',
      id: 'first_name',
      name: 'firstName',
      type: 'text',
      value: 'Иван',
      class: 'block_input block_input_no-background font_13'
    },
    {
      ref: USER_PROFILE_REFS.SECOND_NAME,
      regex: '',
      required: true,
      header: 'Фамилия',
      disabled: 'true',
      id: 'second_name',
      name: 'second_name',
      type: 'text',
      value: 'Иванов',
      class: 'block_input block_input_no-background font_13'
    },
    {
      ref: USER_PROFILE_REFS.DISPLAY_NAME,
      regex: '',
      required: true,
      header: 'Имя в чате',
      disabled: 'true',
      id: 'display_name',
      name: 'display_name',
      type: 'text',
      value: 'Иван',
      class: 'block_input block_input_no-background font_13'
    },
    {
      ref: USER_PROFILE_REFS.PHONE,
      regex: '',
      required: true,
      header: 'Телефон',
      disabled: 'true',
      id: 'phone',
      name: 'phone',
      type: 'text',
      value: '+7 (909) 967 30 30',
      class: 'last block_input block_input_no-background font_13',
    },
  ],
  userProfilePasswordBlock: [
    {
      ref: USER_PROFILE_REFS.PASSWORD,
      regex: '',
      required: true,
      header: 'Старый пароль',
      id: 'oldPassword',
      name: 'password',
      type: 'password',
      value: '1111111',
      class: 'block_input block_input_no-background font_13'
    },
    {
      ref: USER_PROFILE_REFS.NEW_PASSWORD,
      regex: '',
      required: true,
      header: 'Новый пароль',
      id: 'newPassword',
      name: 'newPassword',
      type: 'password',
      value: '123456789',
      class: 'block_input block_input_no-background font_13'
    },
    {
      ref: USER_PROFILE_REFS.REP_NEW_PASSWORD,
      regex: '',
      required: true,
      header: 'Повторите новый пароль',
      id: 'repeatNewPassword',
      name: 'repeatNewPassword',
      type: 'password',
      value: '123456789',
      class: 'last block_input block_input_no-background font_13',
    },
  ],
  userProfileChangeLinks: {
    changeUserData: {
      header: 'Изменить данные',
      isShowButton: 'true',
      class: 'user-profile_change-data-button',
    },
    changeUserPassword: {
      header: 'Изменить пароль',
      isShowButton: 'true',
      class: 'user-profile_change-password-button',
    },
  },
};
